name = "rolldorado-casino-pt"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=rolldorado-casino.pt"
HMAC_KEY = "4076ee568534dc940bd7fa29674915f1705280b7f157e0e649148348f8fab627"
COOKIE_NAME = "e13"
PLAY_PATH = "start"
BUTTON_ID = "p11a24e2a8742437cf522e119499646c3"
GATE_SALT = "0c58cd99259faa7a"
